image: golang:latest

stages:
  - test
  - build

test:
  stage: test
  script:
    - go vet -mod=vendor ./...
    - go test -mod=vendor -cover -race ./...

compile:
  stage: build
  script:
    - go build -mod=vendor -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/uritool
  artifacts:
    paths:
      - uritool
